FROM node:20-alpine AS builder
# Set working directory
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl
RUN npm install -g pnpm turbo

COPY . .
RUN turbo prune --scope=web --docker

FROM node:20-alpine AS installer
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl
RUN npm install -g pnpm

# First install dependencies
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --frozen-lockfile

# Build the project and its dependencies
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json

# Next.js telemetry disable
ENV NEXT_TELEMETRY_DISABLED=1

RUN pnpm turbo run build --filter=web...

FROM node:20-alpine AS runner
WORKDIR /app
RUN apk add --no-cache curl

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Start the Next.js Standalone server
CMD ["node", "apps/web/server.js"]
