"use client";
import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { ShieldAlert, Eye, XCircle, Server, MonitorSmartphone, X, Activity } from 'lucide-react';
import toast from 'react-hot-toast';
import { apiClient } from '@/lib/api/client';

interface VdrVault {
  id: string;
  documentName: string;
  generatedBy: string;
  generatedAt: string;
  status: 'ACTIVE' | 'EXPIRED';
  accessCount: number;
  token: string;
}

interface VdrAccessLog {
  id: string;
  accessedAt: string;
  viewerName: string;
  viewerId: string;
  ipAddress: string;
  userAgent: string;
  action: string;
}

export function VdrTracking() {
  const queryClient = useQueryClient();
  const [selectedVaultToken, setSelectedVaultToken] = useState<string | null>(null);

  const { data: vaults = [], isLoading } = useQuery<VdrVault[]>({
    queryKey: ['vdr-vaults'],
    queryFn: async () => {
      const res = await apiClient.get('/reports/vdr-audit');
      return res.data;
    }
  });

  const { data: auditLogs = [], isLoading: isLoadingLogs } = useQuery<VdrAccessLog[]>({
    queryKey: ['vdr-audit-logs', selectedVaultToken],
    queryFn: async () => {
      const res = await apiClient.get(`/reports/vdr-audit/${selectedVaultToken}`);
      return res.data;
    },
    enabled: !!selectedVaultToken
  });

  const revokeMutation = useMutation({
    mutationFn: async (token: string) => {
      const res = await apiClient.post(`/reports/vdr-audit/${token}/revoke`);
      return res.data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['vdr-vaults'] });
      toast.success('VDR Vault revoked successfully. The link is now dead.');
    }
  });

  return (
    <div className="space-y-6">
      <div className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-200 bg-slate-50 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-indigo-600" />
            <h3 className="font-bold text-slate-900">Active Confidential Vaults</h3>
          </div>
          <div className="text-xs font-semibold text-slate-500 bg-slate-200 px-3 py-1 rounded-full">
            FORENSIC MONITORING ACTIVE
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-200 text-[10px] uppercase tracking-wider font-bold text-slate-500">
                <th className="px-6 py-3">Document Context</th>
                <th className="px-6 py-3">Generated By (HR)</th>
                <th className="px-6 py-3">Generated At</th>
                <th className="px-6 py-3">Status</th>
                <th className="px-6 py-3">Total Views</th>
                <th className="px-6 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-sm">
              {isLoading ? (
                <tr>
                  <td colSpan={6} className="px-6 py-8 text-center text-slate-500 text-xs font-medium">Loading active vaults...</td>
                </tr>
              ) : vaults.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-8 text-center text-slate-500 text-xs font-medium">No secure VDR links have been generated yet.</td>
                </tr>
              ) : vaults.map((vault) => (
                <tr key={vault.id} className="hover:bg-slate-50/50 transition-colors">
                  <td className="px-6 py-4 font-semibold text-slate-900">{vault.documentName.replace(/_/g, ' ')}</td>
                  <td className="px-6 py-4 text-slate-600 font-medium">{vault.generatedBy}</td>
                  <td className="px-6 py-4 text-slate-500 text-xs">{new Date(vault.generatedAt).toLocaleString()}</td>
                  <td className="px-6 py-4">
                    <span className={`px-2.5 py-1 text-[10px] font-bold rounded-full ${
                      vault.status === 'ACTIVE' ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'
                    }`}>
                      {vault.status}
                    </span>
                  </td>
                  <td className="px-6 py-4 font-bold text-slate-800">{vault.accessCount}</td>
                  <td className="px-6 py-4 text-right space-x-2">
                    <button 
                      onClick={() => setSelectedVaultToken(vault.token)}
                      className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 text-xs font-bold rounded-lg transition-colors"
                    >
                      <Eye className="w-3.5 h-3.5" /> Drilldown
                    </button>
                    {vault.status === 'ACTIVE' && (
                      <button 
                        onClick={() => {
                          if (confirm('Are you sure you want to instantly revoke and kill this VDR link?')) {
                            revokeMutation.mutate(vault.token);
                          }
                        }}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-red-50 hover:bg-red-100 text-red-700 text-xs font-bold rounded-lg transition-colors"
                      >
                        <XCircle className="w-3.5 h-3.5" /> Revoke
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Forensic Modal */}
      {selectedVaultToken && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-4xl max-h-[85vh] flex flex-col overflow-hidden border border-slate-200">
            <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between bg-slate-50">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-indigo-100 text-indigo-700 flex items-center justify-center">
                  <Activity className="w-4 h-4" />
                </div>
                <div>
                  <h3 className="font-bold text-slate-900 text-sm">VDR Access Forensics</h3>
                  <p className="text-[10px] font-semibold text-slate-500 uppercase tracking-wider">Vault ID: {selectedVaultToken.split('-')[0]}...</p>
                </div>
              </div>
              <button 
                onClick={() => setSelectedVaultToken(null)}
                className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-lg transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <div className="p-6 overflow-y-auto">
              {isLoadingLogs ? (
                <div className="text-center py-12 text-slate-500 text-sm font-medium flex flex-col items-center gap-3">
                  <Server className="w-8 h-8 animate-pulse text-slate-300" />
                  Extracting forensic logs from database...
                </div>
              ) : auditLogs.length === 0 ? (
                <div className="text-center py-12 text-slate-500 text-sm font-medium">
                  No access logs recorded for this vault yet.
                </div>
              ) : (
                <div className="space-y-4">
                  {auditLogs.map((log) => (
                    <div key={log.id} className="flex flex-col md:flex-row md:items-center justify-between p-4 bg-slate-50 border border-slate-200 rounded-xl gap-4">
                      <div className="flex flex-col gap-1">
                        <div className="flex items-center gap-2">
                          <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                            log.action === 'VIEWED' ? 'bg-blue-100 text-blue-700' : 'bg-orange-100 text-orange-700'
                          }`}>
                            {log.action}
                          </span>
                          <span className="text-xs font-semibold text-slate-500">
                            {new Date(log.accessedAt).toLocaleString()}
                          </span>
                        </div>
                        <div className="text-sm font-bold text-slate-900 mt-1">
                          Viewer: {log.viewerName}
                        </div>
                      </div>

                      <div className="flex items-start gap-4">
                        <div className="flex flex-col gap-1">
                          <div className="flex items-center gap-1.5 text-xs text-slate-600 font-medium">
                            <Server className="w-3.5 h-3.5 text-slate-400" />
                            IP: <span className="font-bold font-mono">{log.ipAddress}</span>
                          </div>
                          <div className="flex items-center gap-1.5 text-xs text-slate-600 font-medium max-w-[200px] truncate" title={log.userAgent}>
                            <MonitorSmartphone className="w-3.5 h-3.5 text-slate-400 flex-shrink-0" />
                            {log.userAgent}
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}